version: "3"

services:
  app:
    image: "python:3.11"
#    environment:
#      PGUSER: pspdfkit
#      PGPASSWORD: password
    volumes:
      - ./app.py:/app/app.py
    entrypoint: ["python3", "/app/app.py"]
    expose:
      - "5000"

  nginx:
    image: nginx:latest
    volumes:
      - ./conf.nginx:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    ports:
      - "4000:4000"